/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-12-24 00:33:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("\t\t<title>Projektledelse</title>\n");
      out.write("\t\t\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"/>\n");
      out.write("    \t<link type=\"text/css\" rel=\"stylesheet\" media=\"screen,projection\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"/>\n");
      out.write("\n");
      out.write("\t\t<script src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("    \t<script src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("    \t<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("    \t<!-- circliful -->\n");
      out.write("    \t<script src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("\n");
      out.write("    \t<!-- Icon font -->\n");
      out.write("    \t<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\n");
      out.write("    \t<link href='https://fonts.googleapis.com/css?family=Roboto|Montserrat' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("\t\t<!--Let browser know website is optimized for mobile-->\n");
      out.write("      \t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("\n");
      out.write("\t</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<!-- Simple header with scrollable tabs - Begin -->\n");
      out.write("\t<div class=\"mdl-layout mdl-js-layout mdl-layout--fixed-header\">\n");
      out.write("\t\t<header class=\"mdl-layout__header\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- Search Row - Begin -->\n");
      out.write("\t\t\t<div class=\"mdmc-container-search\">\n");
      out.write("\t\t\t\t<div class=\"mdl-layout__header-row-dashboard\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Logo -->\n");
      out.write("\t\t\t\t<div class=\"mdlc-dashboard-logo\"></div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Search Box - Begin -->\n");
      out.write("\t\t\t\t<nav clas=\"navbar-fixed\">\n");
      out.write("\t\t\t\t\t<div class=\"nav-wrapper\">\n");
      out.write("\t\t\t\t\t\t<div class=\"mdlc-dashboard-search\">\n");
      out.write("\t\t\t\t\t\t\t<form>\n");
      out.write("\t\t\t\t\t      <div class=\"input-field invalid white-text \">\n");
      out.write("\t\t\t\t\t        <div class=\"material-icons mdmc-prefix-search\">search</div>\n");
      out.write("\t\t\t\t\t          <input type=\"text\" id=\"search\" name=\"search\" placeholder=\"Search\" class=\"mdmc-search-icon-left\">\n");
      out.write("\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t    </form>\n");
      out.write("\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t\t<!-- Search Box - End -->\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Avatar - Begin -->\n");
      out.write("\t\t\t\t<div class=\"mdlc-dashboard-avatar\">\n");
      out.write("\t\t\t\t\t<img src=\"images/Avatar_1.png\" class=\"mdmc-circle-border\">\n");
      out.write("\t\t\t\t\t<img src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\" class=\"mdmc-circle-border\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<span>Renan Chagas</span>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<button id=\"demo-menu-lower-right\" class=\"mdl-button mdl-js-button mdl-button--icon\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"material-icons\">more_vert</i>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<ul class=\"mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect\"\n");
      out.write("\t\t\t\t\t\t\t\tfor=\"demo-menu-lower-right\">\n");
      out.write("\t\t\t\t\t\t\t<li class=\"mdl-menu__item\">Some Action</li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"mdl-menu__item\">Another Action</li>\n");
      out.write("\t\t\t\t\t\t\t<li disabled class=\"mdl-menu__item\">Disabled Action</li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"mdl-menu__item\">Yet Another Action</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- Avatar - End -->\n");
      out.write("\t   \n");
      out.write("\t    \t</div>\n");
      out.write("\t    \t<!-- Search Row - End -->\n");
      out.write("\t    \n");
      out.write("\t    <!-- Tabs -->\n");
      out.write("\t    <div class=\"mdl-layout__tab-bar mdl-js-ripple-effect\">\n");
      out.write("\t      <a href=\"#scroll-tab-1\" class=\"mdl-layout__tab is-active\">My Courses</a>\n");
      out.write("\t      <a href=\"#scroll-tab-2\" class=\"mdl-layout__tab\">Some Action</a>\n");
      out.write("\t      <a href=\"#scroll-tab-3\" class=\"mdl-layout__tab\">Another Action</a>\n");
      out.write("\t      <a href=\"#scroll-tab-4\" class=\"mdl-layout__tab\">Disabled Action</a>\n");
      out.write("\t      <a href=\"#scroll-tab-5\" class=\"mdl-layout__tab\">One Action</a>\n");
      out.write("\t      <a href=\"#scroll-tab-6\" class=\"mdl-layout__tab\">More Action</a>\n");
      out.write("\t    </div>\n");
      out.write("\n");
      out.write("\t  </header>\n");
      out.write("\n");
      out.write("\t  <main class=\"mdl-layout__content\">\n");
      out.write("\n");
      out.write("\t\t<!-- Courses - Begin -->\n");
      out.write("\t   \t<section class=\"mdl-layout__tab-panel is-active\" id=\"scroll-tab-1\">\n");
      out.write("\t    \t<div class=\"page-content\">\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t<div class=\"mdmc-container-card\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("        \t\t\t<div class=\"col s12\">\n");
      out.write("        \t\t\t\n");
      out.write("\t\t\t\t\t<!-- Card Content - Begin -->\n");
      out.write("          \t\t\t<div class=\"card small mdmc-visible mdmc-card-small-350\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- Card Menu - Begin -->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col s12 m6 l8\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Card Menu Title - Begin -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mdmc-dashboard-card-menu\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Courses Availables -->\n");
      out.write("\t\t\t\t\t\t\t<a class=\"mdl-button mdl-js-button dropdown-button mdmc-dashboard-card-menu-margin-left\" \n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" data-activates=\"dropdown-card-title\" data-beloworigin=\"true\">\n");
      out.write("\t\t\t\t\t\t\t\tActive Courses\n");
      out.write("\t\t\t\t\t\t\t<i class=\"tiny material-icons\">expand_more</i>\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Courses Dropdown Structure -->\n");
      out.write("\t\t\t\t\t\t\t\t<ul id='dropdown-card-title'\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"mdmc-dropdown-content-card-title mdmc-box-shadow-min \" constrainwidth=\"false\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#!\">Favorite Courses\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"mdl-badge mdlc-badge-dashboard\" data-badge=\"6\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#!\">Latest Courses\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"mdl-badge mdlc-badge-dashboard\" data-badge=\"4\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#!\">Important Courses\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"mdl-badge mdlc-badge-dashboard\" data-badge=\"5\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- Card Menu Title - End -->\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- Card Menu buttons- Begin -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col s12 m6 l4\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"mdmc-dashboard-card-menu right\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Add Icon -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<button id=\"add_course\" type=\"submit\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn waves-effect waves-light blue mdmc-dashboard-card-menu-margin\"  name=\"Add\">\n");
      out.write("\t                \t\t\t\t\t<i class=\"material-icons left\">add</i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\tAdd\n");
      out.write("\t                \t\t\t\t</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Settings Icon -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<button id=\"card-dashboard-settings\" class=\"mdl-button mdl-js-button mdl-button--icon\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tmdmc-dashboard-card-menu-margin-icon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"material-icons\">settings</i>\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfor=\"card-dashboard-settings\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"mdl-menu__item\">Some Action</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"mdl-menu__item\">Another Action</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li disabled class=\"mdl-menu__item\">Disabled Action</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"mdl-menu__item\">Yet Another Action</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Reorder Icon -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<button id=\"card-dashboard-reorder\" class=\"mdl-button mdl-js-button mdl-button--icon\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tmdmc-dashboard-card-menu-margin-icon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"material-icons\">reorder</i>\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfor=\"card-dashboard-reorder\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"mdl-menu__item\">Some Action</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"mdl-menu__item\">Another Action</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li disabled class=\"mdl-menu__item\">Disabled Action</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"mdl-menu__item\">Yet Another Action</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- Card Menu buttons- End -->\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- Card Menu - End -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Card Main Content - Begin -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Message when no courses are available -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mdmc-container-card-title\" hidden=\"true\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"mdmc-text-align-center mdmc-text-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\tThere are currently no courses available\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Courses Progress - Begin -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Course 1 - Begin -->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mdmc-dashboard-card-courses\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Progress Bar -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"myStat2\" data-dimension=\"200\" data-text=\"70\" data-info=\"Days\" data-width=\"30\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-fontsize=\"38\" data-percent=\"70\" data-fgcolor=\"#2196F3\" data-bgcolor=\"#eee\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"mdmc-dashboard-courses-size \">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"mdmc-dashboard-center mdmc-dashboard-bottom\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tJava\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Course 1 - End -->\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Course 2 - Begin -->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mdmc-dashboard-card-courses\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Progress Bar -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"myStat3\" data-dimension=\"200\" data-text=\"35\" data-info=\"Days\" data-width=\"30\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-fontsize=\"38\" data-percent=\"40\" data-fgcolor=\"#2196F3\" data-bgcolor=\"#eee\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"mdmc-dashboard-courses-size \">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"mdmc-dashboard-center mdmc-dashboard-bottom\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tGBS Security\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Course 2 - End -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- Courses Progress - End -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Expand Card -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mdmc-dashboard-card-expand\">\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"btn-floating btn-large waves-effect waves-light blue\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"material-icons\">expand_more</i>\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- Card Content - End -->\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t    </section>\n");
      out.write("\t    <!-- Courses - END -->\n");
      out.write("\n");
      out.write("\t    <section class=\"mdl-layout__tab-panel\" id=\"scroll-tab-2\">\n");
      out.write("\t      <div class=\"page-content\"><!-- Your content goes here --></div>\n");
      out.write("\t    </section>\n");
      out.write("\t    <section class=\"mdl-layout__tab-panel\" id=\"scroll-tab-3\">\n");
      out.write("\t      <div class=\"page-content\"><!-- Your content goes here --></div>\n");
      out.write("\t    </section>\n");
      out.write("\t    <section class=\"mdl-layout__tab-panel\" id=\"scroll-tab-4\">\n");
      out.write("\t      <div class=\"page-content\"><!-- Your content goes here --></div>\n");
      out.write("\t    </section>\n");
      out.write("\t    <section class=\"mdl-layout__tab-panel\" id=\"scroll-tab-5\">\n");
      out.write("\t      <div class=\"page-content\"><!-- Your content goes here --></div>\n");
      out.write("\t    </section>\n");
      out.write("\t    <section class=\"mdl-layout__tab-panel\" id=\"scroll-tab-6\">\n");
      out.write("\t      <div class=\"page-content\"><!-- Your content goes here --></div>\n");
      out.write("\t    </section>\n");
      out.write("\t  </main>\n");
      out.write("\t  \n");
      out.write("\t</div>\n");
      out.write("\t<!-- Simple header with scrollable tabs - Begin -->\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t$( document ).ready(function(){\n");
      out.write("\n");
      out.write("\t\t\t\t$('#myStat2').circliful();\n");
      out.write("\t\t\t\t$('#myStat3').circliful();\n");
      out.write("\n");
      out.write("\t\t\t\t$('.mdl-button').dropdown({\n");
      out.write("\t\t\t\t\tconstrain_width: false, // Does not change width of dropdown to that of the activator\n");
      out.write("\t\t\t\t\tgutter: 0, // Spacing from edge\n");
      out.write("\t\t\t\t\tbelowOrigin: true, // Displays dropdown below the button\n");
      out.write("\t\t\t\t\talignment: 'left' // Displays dropdown with edge aligned to the left of button\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t//Progress Courses\n");
      out.write("\t\t\t$('#myStat2').hover(function () {\n");
      out.write("\n");
      out.write("\t\t\t\t$('#myStat2').find(\"span.circle-text\").css('font-size','45px');\n");
      out.write("\t\t\t\t$('#myStat2').find(\"span.circle-text\").css('color','#2196F3');\n");
      out.write("\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tfunction () {\n");
      out.write("\t\t\t\t$('#myStat2').find(\"span.circle-text\").css('font-size','38px');\n");
      out.write("\t\t\t\t$('#myStat2').find(\"span.circle-text\").css('color','#000');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t);\n");
      out.write("\n");
      out.write("\t\t\t//Progress Courses\n");
      out.write("\t\t\t$('#myStat3').hover(function () {\n");
      out.write("\n");
      out.write("\t\t\t\t$('#myStat3').find(\"span.circle-text\").css('font-size','45px');\n");
      out.write("\t\t\t\t$('#myStat3').find(\"span.circle-text\").css('color','#2196F3');\n");
      out.write("\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tfunction () {\n");
      out.write("\t\t\t\t$('#myStat3').find(\"span.circle-text\").css('font-size','38px');\n");
      out.write("\t\t\t\t$('#myStat3').find(\"span.circle-text\").css('color','#000');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t);\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/user/dashboard.jsp(8,47) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/static/css/material.css");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/views/user/dashboard.jsp(9,76) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/static/css/materialize.css");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/views/user/dashboard.jsp(11,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/static/js/jquery-2.1.4.min.js");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /WEB-INF/views/user/dashboard.jsp(12,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/static/js/materialize.min.js");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /WEB-INF/views/user/dashboard.jsp(13,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/static/js/material.min.js");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent(null);
    // /WEB-INF/views/user/dashboard.jsp(15,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/static/js/jquery.circliful.js");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f6.setParent(null);
    // /WEB-INF/views/user/dashboard.jsp(56,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f6.setValue("images/Avatar_1.png");
    int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
    if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
    return false;
  }
}
